name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    # This finishes fairly fast, so we can run it using Github's runners
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.2"
          gleam-version: "1.9.1"
          rebar3-version: "3"
      - run: gleam deps download
        working-directory: erlang_template
      - run: gleam test
        working-directory: erlang_template
      # We don't want to format the tablebase data file. Doing so will make it
      # large enough that we have to `gleam clean` before every rebuild.
      - run: |-
          gleam format --check \
            src/*.gleam \
            src/chess/*.gleam \
            src/chess/{actors,evaluate,game,move,search,util} \
            src/util \
            test
        working-directory: erlang_template

  position_test:
    runs-on: [self-hosted, linux, x64]
    env:
      ImageOS: ubuntu24
    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.2"
          gleam-version: "1.9.1"
          rebar3-version: "3"

      - run: gleam deps download
        working-directory: erlang_template

      - run: gleam build
        working-directory: erlang_template

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - run: mkdir -p results

      - name: Run position tests
        # TODO: Tune depth higher as we can search more efficiently
        run: |-
          deno task test \
            --engine ../../scripts/start-uci.sh \
            --workers 4 \
            --timeout 5000  > ${{ github.workspace }}/results/position-tests.md
        working-directory: dev_utils/ci/position-tests

      - name: Find existing PR comment
        if: github.event_name == 'pull_request'
        id: find-comment
        uses: peter-evans/find-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: 'Position Test'

      - name: Post or update PR comment
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v4
        with:
          edit-mode: replace
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body-file: results/position-tests.md
          comment-id: ${{ steps.find-comment.outputs.comment-id }}

