name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  # test:
  #   # This finishes fairly fast, so we can run it using Github's runners
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: erlef/setup-beam@v1
  #       with:
  #         otp-version: "27.1.2"
  #         gleam-version: "1.9.1"
  #         rebar3-version: "3"
  #     - run: gleam deps download
  #       working-directory: erlang_template
  #     - run: gleam test
  #       working-directory: erlang_template
  #     - run: gleam format --check src test
  #       working-directory: erlang_template
  #
  # evaluation_test:
  #   runs-on: self-hosted
  #   steps:
  #     - uses: actions/checkout@v4
  #
  #     - uses: erlef/setup-beam@v1
  #       with:
  #         otp-version: "27.1.2"
  #         gleam-version: "1.9.1"
  #         rebar3-version: "3"
  #
  #     - run: gleam deps download
  #       working-directory: erlang_template
  #
  #     - run: gleam build
  #       working-directory: erlang_template
  #
  #     - name: Install Deno
  #       uses: denoland/setup-deno@v2
  #       with:
  #         deno-version: v2.x
  #
  #     - run: mkdir -p results
  #
  #     - name: Run Bratko-Kopec
  #       run: deno task test > ${{ github.workspace }}/results/bratko-kopec.md
  #       working-directory: dev_utils/ci/bratko-kopec
  #
  #     - name: Upload artifacts
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: bratko-kopec
  #         path: results/
  #
  #     - name: Find existing PR comment
  #       if: github.event_name == 'pull_request'
  #       id: find-comment
  #       uses: peter-evans/find-comment@v3
  #       with:
  #         issue-number: ${{ github.event.pull_request.number }}
  #         comment-author: 'github-actions[bot]'
  #         body-includes: 'Bratko-Kopec Report'
  #
  #     - name: Post or update PR comment
  #       if: github.event_name == 'pull_request'
  #       uses: peter-evans/create-or-update-comment@v4
  #       with:
  #         edit-mode: replace
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         issue-number: ${{ github.event.pull_request.number }}
  #         body-file: results/bratko-kopec.md
  #         comment-id: ${{ steps.find-comment.outputs.comment-id }}

  sprt:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.2"
          gleam-version: "1.9.1"
          rebar3-version: "3"

      - run: gleam deps download
        working-directory: erlang_template

      - run: gleam build
        working-directory: erlang_template

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run SPRT
        run: dev_utils/ci/sprt/start.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sprt
          path: results/
