name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    # This finishes fairly fast, so we can run it using Github's runners
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.2"
          gleam-version: "1.9.1"
          rebar3-version: "3"
      - run: gleam deps download
        working-directory: erlang_template
      - run: gleam test
        working-directory: erlang_template
      - run: gleam format --check src test
        working-directory: erlang_template

  evaluation_test:
    runs-on: [self-hosted, linux, x64]
    env:
      ImageOS: ubuntu24
    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.2"
          gleam-version: "1.9.1"
          rebar3-version: "3"

      - run: gleam deps download
        working-directory: erlang_template

      - run: gleam build
        working-directory: erlang_template

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - run: mkdir -p results

      - name: Run Bratko-Kopec
        # TODO: Tune depth higher as we can search more efficiently
        run: |-
          deno task test \
            --engine ../../scripts/start-uci.sh \
            --workers 4 \
            --timeout 10000 \
            --depth 8 > ${{ github.workspace }}/results/bratko-kopec.md
        working-directory: dev_utils/ci/bratko-kopec

      - name: Find existing PR comment
        if: github.event_name == 'pull_request'
        id: find-comment
        uses: peter-evans/find-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: 'Bratko-Kopec Report'

      - name: Post or update PR comment
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v4
        with:
          edit-mode: replace
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body-file: results/bratko-kopec.md
          comment-id: ${{ steps.find-comment.outputs.comment-id }}

  sprt-stockfish:
    runs-on: [self-hosted, linux, x64, fast]
    env:
      ImageOS: ubuntu24
    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.2"
          gleam-version: "1.9.1"
          rebar3-version: "3"

      - run: gleam deps download
        working-directory: erlang_template

      - run: gleam build
        working-directory: erlang_template

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Deno dependencies
        run: deno install
        working-directory: dev_utils/ci/sprt

      - name: Run SPRT against Stockfish
        run: dev_utils/ci/sprt/stockfish.sh

      - name: Upload results
        env:
          LICHESS_KEY: ${{ secrets.LICHESS_KEY }}
        run: >-
          deno run -A upload-report.ts \
            --pgn "${{ github.workspace }}/results/stockfish.pgn" \
            --title "Us vs. Stockfish" > "${{ github.workspace }}/results/us-vs-stockfish.md"
        working-directory: dev_utils/ci/sprt

      - name: Find existing PR comment
        if: github.event_name == 'pull_request'
        id: find-comment
        uses: peter-evans/find-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: 'Us vs. Stockfish'

      - name: Post or update PR comment
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v4
        with:
          edit-mode: replace
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body-file: results/us-vs-stockfish.md
          comment-id: ${{ steps.find-comment.outputs.comment-id }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sprt-stockfish
          path: results/

  sprt-regression:
    runs-on: [self-hosted, linux, x64, fast]
    env:
      ImageOS: ubuntu24
      REGISTRY: ghcr.io

    steps:
      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true

      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.2"
          gleam-version: "1.9.1"
          rebar3-version: "3"

      - run: gleam deps download
        working-directory: erlang_template

      - run: gleam build
        working-directory: erlang_template

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Deno dependencies
        run: deno install
        working-directory: dev_utils/ci/sprt

      - name: Run SPRT against ourselves
        run: dev_utils/ci/sprt/regression.sh

      - name: Upload results
        env:
          LICHESS_KEY: ${{ secrets.LICHESS_KEY }}
        run: >-
          deno run -A upload-report.ts \
            --pgn "${{ github.workspace }}/results/regression.pgn" \
            --title "Defender vs. Challenger" > "${{ github.workspace }}/results/defender-vs-challenger.md"
        working-directory: dev_utils/ci/sprt

      - name: Find existing PR comment
        if: github.event_name == 'pull_request'
        id: find-comment
        uses: peter-evans/find-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: 'Defender vs. Challenger'

      - name: Post or update PR comment
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v4
        with:
          edit-mode: replace
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body-file: results/defender-vs-challenger.md
          comment-id: ${{ steps.find-comment.outputs.comment-id }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sprt-regression
          path: results/
